name: brick_cloud_firestore
description: Cloud Firestore connector for Brick

version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: '>=1.9.0 <2.0.0'

dependencies:
  brick_core: ^0.0.5
  brick_offline_first: any
  brick_cloud_firestore_abstract: any
  cloud_firestore: any
  flutter:
    sdk: flutter
  meta: '>=1.1.6 <2.0.0'

dependency_overrides:
  brick_cloud_firestore_abstract:
    path: ../brick_cloud_firestore_abstract

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  test: '>=1.9.4 <2.0.0'
